import React,{useEffect,useState} from 'react';
import { useLocation,useNavigate,Link } from 'react-router-dom';
import { MessageCircleMore,ClipboardCheck,FileText,Mic,Send,Languages,Check,ArrowLeft,Users } from 'lucide-react';
const langs=['English','中文 Chinese','Tiếng Việt Vietnamese','العربية Arabic','Español Spanish','한국어 Korean'];
export default function IntakeFlow(){const {pathname}=useLocation(),nav=useNavigate();const [loading,setLoading]=useState(false);const [step,setStep]=useState(3);useEffect(()=>{if(pathname==='/intake/processing'){const t=setTimeout(()=>nav('/intake-summary'),1700);return()=>clearTimeout(t)}},[pathname]);
if(pathname==='/intake')return <div className="intake-card"><p className="eyebrow">A safe place to begin</p><h1>Welcome to Lou’s Place</h1><p className="lead">Choose how you would like to share what brings you here today.</p><div className="method-grid">{[[MessageCircleMore,'Talk with LouOS','Tell us what brings you here in your own words.','Start Conversation','conversation'],[ClipboardCheck,'Guided Questions','Answer a few simple questions at your own pace.','Start Questions','guided'],[FileText,'Paper Form','Prefer paper? Complete the existing form with a staff member.','Continue with Paper Form','paper']].map(([I,t,d,b,p])=><div className="method" key={t}><I/><h2>{t}</h2><p>{d}</p><Link className="primary" to={`/intake/${p==='paper'?'paper':'language'}?mode=${p}`}>{b}</Link></div>)}</div></div>;
if(pathname.includes('language'))return <div className="intake-card narrow"><Languages className="hero-icon"/><h1>Choose your preferred language</h1><p className="lead">You can change this later or ask a team member for help.</p><div className="language-grid">{langs.map(l=><Link key={l} to={`/intake/${location.search.includes('guided')?'guided':'conversation'}`}>{l}<span>›</span></Link>)}</div><button className="text-button">More languages</button></div>;
if(pathname.includes('conversation'))return <div className="conversation"><header><div><h2>LouOS Intake</h2><span><Languages size={14}/>Vietnamese selected</span></div><BadgeText/></header><div className="messages">{[['bot','Welcome. You can take your time. What brought you to Lou’s Place today?'],['client','I left my partner recently and I’m staying with a friend. I have two children and I’m worried I won’t have anywhere to stay after Monday.'],['bot','Thank you for sharing that. Do you feel safe where you are staying tonight?'],['client','Yes, tonight is okay.'],['bot','Is finding somewhere safe to stay after Monday the most important thing you would like help with today?'],['client','Yes, and I’m also worried about money.']].map((m,i)=><div className={`bubble ${m[0]}`} key={i}><small>{m[0]==='bot'?'LouOS':'You'}</small>{m[1]}</div>)}</div><div className="chat-compose"><button><Mic/></button><input placeholder="Share what you would like the team to know…"/><button><Send/></button></div><Link className="primary complete" to="/intake/processing">Complete Intake</Link></div>;
if(pathname.includes('guided'))return <div className="intake-card guided"><div className="progress"><span style={{width:`${step/7*100}%`}}/></div><p className="eyebrow">Step {step} of 7</p><h1>{step===3?'What would you like support with?':step===4?'Are children or dependants currently with you?':'How urgent does your situation feel?'}</h1><div className="choices">{(step===3?['Housing / Accommodation','Safety','Financial Support','Family / Domestic Violence','Legal Support','Health / Wellbeing','Employment','Family / Children','Other']:step===4?['Yes','No','Prefer not to say']:['I need help immediately','I need help soon','I am looking for general support']).map(x=><button key={x} onClick={e=>e.currentTarget.classList.toggle('selected')}><Check/>{x}</button>)}</div><div className="form-actions"><button className="secondary" onClick={()=>setStep(Math.max(3,step-1))}><ArrowLeft/>Back</button><button className="text-button">Skip</button>{step<5?<button className="primary" onClick={()=>setStep(step+1)}>Continue</button>:<Link className="primary" to="/intake/processing">Finish Intake</Link>}</div></div>;
if(pathname.includes('paper'))return <div className="intake-card narrow"><FileText className="hero-icon"/><h1>Paper Intake</h1><p className="lead">A Lou’s Place team member can assist you with the existing paper intake process.</p><div className="paper-preview"><div className="paper-lines"/><div className="paper-lines short"/><div className="paper-boxes"/><div className="paper-lines"/></div><button className="primary" onClick={()=>{setLoading(true);setTimeout(()=>nav('/intake/processing'),1200)}}>{loading?'Reading intake form…':'Demo: Extract Information'}</button></div>;
return <div className="processing"><div className="pulse-logo">Lou<span>OS</span></div><h1>Preparing your intake summary…</h1>{['Understanding your information','Identifying support areas','Checking urgency'].map(x=><p key={x}><Check/> {x}</p>)}<p className="working"><span/> Preparing staff handover…</p></div>}
function BadgeText(){return <span className="client-confirmed">Client-led intake</span>}