import React from 'react';

const Field=({label,value})=><div className="sr-field"><span>{label}</span><b>{value||'Not recorded'}</b></div>;
export default function RecordCaseReport({record,approved}){
  const name=record.preferred_name||record.client_name||'Client';
  const problems=record.problems||[];
  const urgency=problems.some(x=>x.priority?.toLowerCase()==='high')?'High':'Standard';
  const facts=[...(record.key_information||[]),...approved.map(x=>x.text)];
  return <div className="sr-report"><section className="sr-card"><h2>Case Information</h2><div className="sr-info"><Field label="Case ID" value={record.form_id||record.id}/><Field label="Date" value={new Date(record.created_date).toLocaleDateString('en-AU')}/><Field label="Status" value={record.status}/><Field label="Urgency" value={urgency}/></div></section><section className="sr-card"><h2>Client Information</h2><div className="sr-info"><Field label="Name" value={record.client_name}/><Field label="Preferred name" value={record.preferred_name}/><Field label="Age" value={record.age}/><Field label="Language" value={record.preferred_language}/><Field label="Contact" value={record.contact}/><Field label="Safe contact" value={record.safe_contact}/><Field label="Dependants" value={record.dependants}/><Field label="Accommodation" value={record.accommodation}/></div></section><section className="sr-card sr-main-need"><span>What does {name} want help with today?</span><h2>{record.main_need||'Support need not recorded'}</h2></section><section className="sr-card"><h2>Current Problems / Crises</h2><div className="sr-problems">{problems.length?problems.map((item,index)=><article className="sr-problem" key={`${item.category}-${index}`}><header><h3>{item.category||'General'}</h3><span className={`sr-badge ${item.priority?.toLowerCase()==='high'?'high':'medium'}`}>{item.priority||'Not set'}</span></header><p>{item.description||'No description recorded.'}</p></article>):<p>No current problems recorded.</p>}</div></section><section className="sr-card"><h2>Case Description</h2><p className="sr-description">{record.summary||'No case description recorded.'}</p></section><section className="sr-card"><h2>Key Information</h2>{facts.length?<ul className="sr-key-list">{facts.map((fact,index)=><li key={`${fact}-${index}`}>{fact}</li>)}</ul>:<p>No key information recorded.</p>}</section></div>
}