import React from 'react';

const Field=({label,value})=><div className="sr-field"><span>{label}</span><b>{value||'Not recorded'}</b></div>;
export default function RecordCaseReport({record,approved}){
  const name=record.preferred_name||record.client_name||'Client';
  const problems=record.problems||[];
  const supportAreas=record.support_areas||problems.map(item=>item.category).filter(Boolean);
  const facts=[...(record.key_information||[]),...approved.map(x=>x.text)];
  const formDate=record.form_date||record.created_date;
  return <div className="sr-report"><section className="sr-card"><h2>Case Information</h2><div className="sr-info"><Field label="Case ID" value={record.form_id||record.id}/><Field label="Form date" value={formDate?new Date(formDate).toLocaleDateString('en-AU'):''}/><Field label="Status" value={record.status}/><Field label="Signature" value={record.signature_present?'Present':'Not recorded'}/></div></section><section className="sr-card"><h2>About you</h2><div className="sr-info"><Field label="Your name" value={record.client_name}/><Field label="What should we call you?" value={record.preferred_name}/><Field label="Age" value={record.age}/><Field label="Language you prefer" value={record.preferred_language}/><Field label="Phone" value={record.contact}/><Field label="Children" value={record.dependants}/><Field label="Where are you staying now?" value={record.accommodation}/><Field label="How long can you stay there?" value={record.stay_duration}/></div></section><section className="sr-card sr-main-need"><span>Why did {name} come to Lou’s Place today?</span><h2>{record.reason_today||record.main_need||'Not recorded'}</h2></section><section className="sr-card"><h2>What’s going on right now</h2><div className="sr-problems">{supportAreas.length?supportAreas.map((area,index)=><article className="sr-problem" key={`${area}-${index}`}><header><h3>{area}</h3></header>{area==='Something else'&&record.support_other&&<p>{record.support_other}</p>}</article>):<p>Nothing selected.</p>}</div></section><section className="sr-card"><h2>Anything else</h2><p className="sr-description">{record.other_help||'Not recorded'}</p></section><section className="sr-card"><h2>Case summary</h2><p className="sr-description">{record.summary||'No case summary recorded.'}</p></section><section className="sr-card"><h2>Key Information</h2>{facts.length?<ul className="sr-key-list">{facts.map((fact,index)=><li key={`${fact}-${index}`}>{fact}</li>)}</ul>:<p>No key information recorded.</p>}</section></div>
}
