import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {Search,Database,FileText} from 'lucide-react';
import {base44} from '@/api/base44Client';

export default function CaseRecords(){
  const[records,setRecords]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState('');
  useEffect(()=>{base44.entities.IntakeDocument.list('-created_date',100).then(setRecords).catch(()=>setError('Case records could not be loaded.')).finally(()=>setLoading(false))},[]);
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?records.filter(r=>[r.form_id,r.client_name,r.preferred_name,r.main_need].some(value=>String(value||'').toLowerCase().includes(q))):records},[records,query]);
  return <main className="mvp-main database-page"><header className="database-head"><div><p className="mvp-kicker">Secure case database</p><h1>All case records</h1><p>Approved intake forms and their extracted case information.</p></div><span className="record-count"><Database size={18}/>{records.length} records</span></header><label className="database-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by Form ID, client, or support need"/></label>{loading?<div className="database-state">Loading case records…</div>:error?<div className="paper-error">{error}</div>:visible.length===0?<div className="database-state">{query?'No matching case records.':'No approved case records yet.'}</div>:<div className="record-list">{visible.map(record=><details className="record-card" key={record.id}><summary><div><b>{record.client_name||'Client name unavailable'}</b><span>{record.form_id||`Record ${record.id.slice(0,8)}`}</span></div><span className="pill">{record.status||'saved'}</span></summary><div className="record-details"><p><b>Main support need</b>{record.main_need||'Not recorded'}</p><p><b>Summary</b>{record.summary||'Not recorded'}</p><p><b>Contact</b>{record.contact||'Not recorded'}</p><p><b>Accommodation</b>{record.accommodation||'Not recorded'}</p><p><b>Key information</b>{(record.key_information||[]).join(' · ')||'Not recorded'}</p><Link className="mvp-btn record-report-link" to={`/casework/${record.id}`}><FileText size={17}/>Open Case Report</Link></div></details>)}</div>}</main>
}