import React,{useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {ArrowRight} from 'lucide-react';
import ReturnButton from '@/components/portal/ReturnButton';
import {base44} from '@/api/base44Client';
import '@/simple-report.css';
import SimpleCaseReport from '@/components/living/SimpleCaseReport';
import SimpleNoteAssistant from '@/components/living/SimpleNoteAssistant';
import RecordCaseReport from '@/components/living/RecordCaseReport';
import RecordNoteAssistant from '@/components/living/RecordNoteAssistant';
export default function CaseworkerWork(){const{recordId}=useParams();const[approved,setApproved]=useState([]),[record,setRecord]=useState(null),[loading,setLoading]=useState(Boolean(recordId)),[error,setError]=useState('');useEffect(()=>{if(!recordId)return;setApproved([]);base44.entities.IntakeDocument.get(recordId).then(setRecord).catch(()=>setError('This case record could not be loaded.')).finally(()=>setLoading(false))},[recordId]);if(loading)return <main className="sr-page"><div className="sr-wrap">Loading case report…</div></main>;if(error)return <main className="sr-page"><div className="sr-wrap"><p className="paper-error">{error}</p><Link className="sr-primary" to="/database">Return to database</Link></div></main>;const isRecord=Boolean(record);const name=isRecord?(record.client_name||'Client name unavailable'):'Sarah Nguyen';const caseId=isRecord?(record.form_id||record.id):'LP-2026-0251';const high=isRecord&&record.problems?.some(x=>x.priority?.toLowerCase()==='high');const approve=item=>setApproved(items=>items.some(x=>x.id===item.id)?items:[...items,item]);return <main className="sr-page"><div className="sr-wrap"><ReturnButton variant="inline" to="/database" label="Back to the database" text="Back to Database"/><header className="sr-heading"><div><p>Living Case Report · {isRecord?'Saved intake record':'Fictional demo client'}</p><h1>{name}</h1><p>Case {caseId}{!isRecord?' · Maya Chen · Senior Caseworker · Housing and DFV':''}</p></div><div className="sr-case-badges"><span className="sr-badge">Active case</span>{(high||!isRecord)&&<span className="sr-badge high">High urgency</span>}<span className="sr-badge medium">{isRecord?(record.main_need||'Support priority'):'Housing priority'}</span></div></header><div className="sr-layout">{isRecord?<RecordCaseReport record={record} approved={approved}/>:<SimpleCaseReport approved={approved}/>} {isRecord?<RecordNoteAssistant onApprove={approve}/>:<SimpleNoteAssistant onApprove={approve}/>}</div><footer className="sr-footer"><Link to="/external-help">Finish caseworker phase <ArrowRight size={15}/></Link></footer></div></main>}