import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,Check} from 'lucide-react';
const workers=[['Maya Chen','Senior Caseworker','Housing & family safety'],['Sophie Kim','Caseworker','General & financial support'],['Daniela Ross','Senior Caseworker','Legal & advocacy']];
const fallback={caseId:'LP-0251',draft:{problems:[{category:'Housing',priority:'High'},{category:'Safety',priority:'High'},{category:'Financial',priority:'Medium'}],keyInformation:['Temporarily staying with a friend until Monday.','Two dependent children are currently with the client.','Current accommodation is safe tonight.','Limited funds available; Centrelink is active.'],mainSupportNeed:'Safe and stable accommodation after Monday.',caseDescription:''}};
export default function SummaryAllocation(){
  const [selected,setSelected]=useState(0),stored=sessionStorage.getItem('louosOnlineReport'),report=stored?JSON.parse(stored):fallback,draft=report.draft;
  const structured=draft.caseOverview?draft:null;
  const needs=structured?[structured.supportNeeds.primaryNeed,...structured.supportNeeds.secondaryNeeds].filter(Boolean):draft.problems?.map(problem=>`${problem.category} · ${problem.priority}`)||[];
  const facts=structured?[structured.presentingSituation.summary,structured.presentingSituation.recentChanges,...structured.safety.concerns].filter(Boolean):(draft.keyInformation?.length?draft.keyInformation:[draft.caseDescription].filter(Boolean));
  const mainNeed=structured?.supportNeeds.primaryNeed||draft.mainSupportNeed;
  return <main className="mvp-main"><header className="mvp-title"><p className="mvp-kicker">{stored?'Online intake complete':'Dummy intake complete'} · {report.caseId}</p><h1>Summary report</h1><p>Review the AI-structured intake information, then choose a suitable caseworker.</p></header><div className="summary-layout"><section><article className="mvp-card"><h2>Primary needs</h2><div className="facts">{needs.map(need=><span className="pill" key={need}>{need}</span>)}</div></article><article className="mvp-card"><h2>Current situation</h2><div className="fact-list">{facts.map(fact=><p key={fact}>{fact}</p>)}</div></article>{mainNeed&&<div className="client-quote">“{mainNeed}”</div>}</section><aside className="mvp-card"><h2>Recommended caseworkers</h2>{workers.map((worker,index)=><button className={`worker ${selected===index?'selected':''}`} onClick={()=>setSelected(index)} key={worker[0]}><span className="worker-avatar">{worker[0].split(' ').map(name=>name[0]).join('')}</span><b>{worker[0]}<span>{worker[1]} · {worker[2]}</span></b>{selected===index&&<Check size={18}/>}</button>)}<Link className="mvp-btn full" to="/casework">Continue with {workers[selected][0]} <ArrowRight/></Link></aside></div></main>;
}
