// One-off seed script for the ExternalOrganization directory used by the Referral
// Pathway. Run with the Base44 CLI (reads this file from stdin):
//
//   cat base44/scripts/seed-external-organizations.ts | npx base44 exec --local --privileged
//   cat base44/scripts/seed-external-organizations.ts | npx base44 exec --privileged   (deployed app)
//
// These are real, well-known NSW/national entry-point and specialist phone
// services (Link2Home, 1800RESPECT, the NSW Mental Health Line, Lifeline,
// LawAccess NSW, Vinnies NSW, the Salvation Army NSW assessment line, and
// eheadspace) — chosen because their contact details are stable and
// independently verifiable (source_url on every record), unlike a specific
// local shelter's direct line, which this project has no way to verify
// automatically. This is curated, periodically-refreshed data, not a live
// feed — add more granular local services here once someone at Lou's Place
// has verified them.

const organizations = [
  { name: 'Link2Home', service_types: ['Homelessness information, assessment and referral', 'Emergency accommodation referral'], client_groups: ['Adults', 'Families', 'Young people'], eligibility: ['Anyone in NSW who is homeless or at risk of homelessness'], eligibility_structured: {}, languages: ['English', 'Interpreter service (TIS National)'], locations: ['NSW'], service_area: 'NSW (statewide)', support_levels: ['Low', 'Medium', 'High', 'Immediate'], availability: 'Phone line answered 24/7', hours: { is24_7: true, hours_note: 'Full accommodation and support referrals only available 9am–10pm daily; overnight calls (10pm–9am) receive safety information and assessment only, with referral to emergency services if needed.' }, availability_status: 'unknown', capacity_note: 'Not publicly available — Link2Home assesses and refers case-by-case.', referral_method: 'Self-referral by phone', referral_method_type: 'phone', contact: '1800 152 152', notes: 'NSW Government’s statewide homelessness information, assessment and referral line. Refers on to specific accommodation/support services rather than being the accommodation itself.', source: 'curated', source_url: 'https://www.nsw.gov.au/housing-and-construction/if-you-need-emergency-accommodation', confidence: 'high', active: true },
  { name: '1800RESPECT', service_types: ['Domestic, family and sexual violence counselling', 'Safety planning', 'Referral'], client_groups: ['Women', 'Men', 'People affected by family or sexual violence'], eligibility: ['Anyone in Australia experiencing or at risk of domestic, family or sexual violence'], eligibility_structured: { dfv_related: true }, languages: ['English', 'Interpreter service'], locations: ['NSW', 'National'], service_area: 'National', support_levels: ['Medium', 'High', 'Immediate'], availability: 'Phone, text and online chat available 24/7', hours: { is24_7: true }, availability_status: 'unknown', capacity_note: 'Not publicly available — contact to confirm.', referral_method: 'Self-referral by phone, text or online chat', referral_method_type: 'phone', contact: '1800 737 732', notes: 'National DFV counselling and referral line.', source: 'curated', source_url: 'https://1800respect.org.au/calling-1800respect', confidence: 'high', active: true },
  { name: 'NSW Mental Health Line', service_types: ['Mental health advice', 'Crisis triage', 'Referral to NSW Health mental health services'], client_groups: ['Adults', 'Young people', 'Families'], eligibility: ['Anyone in NSW concerned about their or someone else’s mental health'], eligibility_structured: {}, languages: ['English', 'Interpreter service'], locations: ['NSW'], service_area: 'NSW (statewide)', support_levels: ['Medium', 'High', 'Immediate'], availability: 'Phone line answered 24/7', hours: { is24_7: true }, availability_status: 'unknown', capacity_note: 'Not publicly available — contact to confirm.', referral_method: 'Self-referral by phone', referral_method_type: 'phone', contact: '1800 011 511', notes: 'Free statewide NSW Health triage and referral line.', source: 'curated', source_url: 'https://www.health.nsw.gov.au/mentalhealth/Pages/mental-health-line.aspx', confidence: 'high', active: true },
  { name: 'Lifeline', service_types: ['Crisis support', 'Suicide prevention counselling'], client_groups: ['Adults', 'Young people'], eligibility: ['Anyone in Australia experiencing a personal crisis or thinking about suicide'], eligibility_structured: {}, languages: ['English', 'Interpreter service'], locations: ['NSW', 'National'], service_area: 'National', support_levels: ['High', 'Immediate'], availability: 'Phone, text and online chat available 24/7', hours: { is24_7: true }, availability_status: 'unknown', capacity_note: 'Not publicly available — contact to confirm.', referral_method: 'Self-referral by phone, text or online chat', referral_method_type: 'phone', contact: '13 11 14', notes: 'National crisis support line.', source: 'curated', source_url: 'https://www.lifeline.org.au/about/contact-us', confidence: 'high', active: true },
  { name: 'LawAccess NSW (Legal Aid NSW)', service_types: ['Legal information', 'Legal referral', 'Some legal advice'], client_groups: ['Adults'], eligibility: ['Anyone in NSW with a legal problem; some services are means-tested'], eligibility_structured: { income_tested: true }, languages: ['English', 'Interpreter service'], locations: ['NSW'], service_area: 'NSW (statewide)', support_levels: ['Low', 'Medium', 'High'], availability: 'Phone line Mon–Fri 9am–5pm', hours: { mon: { open: '09:00', close: '17:00' }, tue: { open: '09:00', close: '17:00' }, wed: { open: '09:00', close: '17:00' }, thu: { open: '09:00', close: '17:00' }, fri: { open: '09:00', close: '17:00' } }, availability_status: 'unknown', capacity_note: 'Not publicly available — contact to confirm.', referral_method: 'Self-referral by phone', referral_method_type: 'phone', contact: '1300 888 529', notes: 'Free government legal information and referral line; refers on to Legal Aid NSW or a community legal centre as appropriate.', source: 'curated', source_url: 'https://www.legalaid.nsw.gov.au/', confidence: 'high', active: true },
  { name: 'Vinnies NSW (St Vincent de Paul Society)', service_types: ['Food and everyday essentials', 'Emergency financial assistance', 'Referral'], client_groups: ['Adults', 'Families'], eligibility: ['Anyone in NSW experiencing financial hardship'], eligibility_structured: {}, languages: ['English', 'Interpreter service'], locations: ['NSW'], service_area: 'NSW (statewide, via local conferences)', support_levels: ['Low', 'Medium', 'High'], availability: 'Phone line Mon–Fri 9am–5pm', hours: { mon: { open: '09:00', close: '17:00' }, tue: { open: '09:00', close: '17:00' }, wed: { open: '09:00', close: '17:00' }, thu: { open: '09:00', close: '17:00' }, fri: { open: '09:00', close: '17:00' } }, availability_status: 'unknown', capacity_note: 'Not publicly available — contact to confirm.', referral_method: 'Self-referral by phone or email', referral_method_type: 'phone', contact: '13 18 12', notes: 'Connects to the nearest local Vinnies conference for material and financial assistance.', source: 'curated', source_url: 'https://www.vinnies.org.au/nsw/find-help/assistance-with-food-and-everyday-essentials', confidence: 'high', active: true },
  { name: 'Salvation Army NSW — Phone Assessment Line', service_types: ['Emergency financial assistance', 'Material aid', 'Referral'], client_groups: ['Adults', 'Families'], eligibility: ['Anyone in NSW experiencing financial hardship'], eligibility_structured: {}, languages: ['English', 'Interpreter service'], locations: ['NSW'], service_area: 'NSW (statewide)', support_levels: ['Low', 'Medium', 'High'], availability: 'Phone line Mon–Fri 9am–4pm', hours: { mon: { open: '09:00', close: '16:00' }, tue: { open: '09:00', close: '16:00' }, wed: { open: '09:00', close: '16:00' }, thu: { open: '09:00', close: '16:00' }, fri: { open: '09:00', close: '16:00' } }, availability_status: 'unknown', capacity_note: 'Not publicly available — contact to confirm.', referral_method: 'Self-referral by phone', referral_method_type: 'phone', contact: '02 8775 7988', notes: 'NSW emergency relief assessment line.', source: 'curated', source_url: 'https://www.salvationarmy.org.au/sydneysalvos/support-services/financial-assistance/', confidence: 'medium', active: true },
  { name: 'eheadspace', service_types: ['Youth mental health counselling', 'Online and phone support'], client_groups: ['Young people'], eligibility: ['Young people aged 12–25'], eligibility_structured: { min_age: 12, max_age: 25 }, languages: ['English'], locations: ['NSW', 'National'], service_area: 'National (online/phone)', support_levels: ['Low', 'Medium', 'High'], availability: 'Hours vary — check website for current phone/chat hours', hours: { hours_note: 'Published hours vary between sources at time of writing — confirm current hours on the headspace website before relying on them.' }, availability_status: 'unknown', capacity_note: 'Not publicly available — contact to confirm.', referral_method: 'Self-referral by phone or online chat', referral_method_type: 'phone', contact: '1800 650 890', notes: 'National online/phone youth mental health service, part of headspace.', source: 'curated', source_url: 'https://headspace.org.au/online-and-phone-support/connect-with-us/faqs/', confidence: 'medium', active: true }
];

const now = new Date().toISOString();
const existing = await base44.entities.ExternalOrganization.list();
const existingNames = new Set(existing.map((item: any) => item.name));
let created = 0;
for (const organization of organizations) {
  if (existingNames.has(organization.name)) continue;
  await base44.entities.ExternalOrganization.create({ ...organization, retrieved_at: now, last_verified_at: now });
  created++;
}
console.log(`Seeded ${created} of ${organizations.length} organisations (${existing.length} already present).`);
